apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: suber
  name: suber
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: suber
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: suber
    spec:
      containers:
      - image: chanwit/suber
        imagePullPolicy: Always
        name: suber
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
